services:
  mysql:
    image: mysql:8.4
    container_name: emr-mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: emr_dev
      MYSQL_USER: emr_user
      MYSQL_PASSWORD: local_emr_password
      MYSQL_ROOT_PASSWORD: local_root_password
      TZ: Asia/Colombo

    ports:
      - "3307:3306"

    volumes:
      - emr_mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-plocal_root_password",
        ]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  emr_mysql_data: